### ISSUE TITLE
Contact ?

### ISSUE THREAD

**Issue by ParadoxalManiak** [AhMyth/AhMyth-Android-RAT#10]
How can I get in touch with you ? I'm a developer myself and I have found some bugs in your code that I can help you fix but I want to ask you some questions about the apk builder since I want to build a custom version.

**Comment by p1vynodejs** [comment]
you can decode the source and edit it yourself. I've done that and added some features on it

**Comment by AhMyth** [comment]
@ParadoxalManiak , you can submit the bugs through pull requests and you can ask me here regarding the apk builder.
@p1vynodejs I will upload the java files soon.
