### ISSUE TITLE
can not connect / does not show victims.

### ISSUE THREAD

**Issue by bytedeez** [AhMyth/AhMyth-Android-RAT#11]
anti virus disabled / AhMyth.apk set to be on from "victim" device.
source IP: on client set to wan ip.
port set and forwarded.

ahMyth running on "victim" IP however nothing shows on client app.
Running on windows 10 64 bit.
Please Advise.

**Comment by AhMyth** [comment]
do you check if the port is available publicly ?

**Comment by usama7628674** [comment]
I just tested it on lan and wan with port forwarded and it works like a charm but camera is not working other than that all functions are working fine.

**Comment by usama7628674** [comment]
Please add some cool features in next release.I really like the GUI and it's very plain and simple to use

**Comment by AhMyth** [comment]
@usama7628674 Yes I will.
Thank you.
