### ISSUE TITLE
Client does not connect to the server

### ISSUE THREAD

**Issue by NeverMine17** [AhMyth/AhMyth-Android-RAT#114]
### What I checked:
  - Ports are opened
  - The IP provided in APK is available and correct
  - Java is correctly installed

### Info
  - Server running on Windows 10 1809
  - java version "1.8.0_191"
  - Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
  - Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
  - Client running on Android 8.1.0
  - AhMyth Rat version is v1.0-beta.1 (9000392) 64bit version
  - Logcat: https://pastebin.com/4vk5S49b

**Comment by b1n4ry21** [comment]
I also have same problem.. client not connect

**Comment by rocco8620** [comment]
@b1n4ry21 looks like is a permission issue (logcat line "process is not permitted to  auto start"

**Comment by NeverMine17** [comment]
@rocco8620 How to fix that? I can't find autostart in my app settings

**Comment by zAlex01** [comment]
same problem

**Comment by NeverMine17** [comment]
@zAlex01 Can you send your logcat from your phone?

**Comment by NeverMine17** [comment]
Related issues: #130

**Comment by NeverMine17** [comment]
@AhMyth

**Comment by MRFOX777** [comment]
Same Problem Plz Solve this

**Comment by NeverMine17** [comment]
I don't think it's possible to fix this issue any time soon. This line in my logcat indicates that Android itself blocked an execution of this rat:
```
12-30 18:11:49.939  3560  3583 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_RESTARTED dat=package:ahmyth.mine.king.ahmyth flg=0x10 (has extras) } to com.mgoogle.android.gms/org.microg.nlp.PackageReceiver
```
[Android Developers states](https://developer.android.com/about/versions/oreo/background) that this is a new mechanism, introduced in Android Oreo (what I was using), to make apps use less resources when they don't need it:

> Whenever an app runs in the background, it consumes some of the device's limited resources, like RAM. This can result in an impaired user experience, especially if the user is using a resource-intensive app, such as playing a game or watching video. To improve the user experience, Android 8.0 (API level 26) imposes limitations on what apps can do while running in the background.

To prevent this from happening, AhMyth must avoid the [Background Service Limitations](https://developer.android.com/about/versions/oreo/background#services):
> Services running in the background can consume device resources, potentially resulting in a worse user experience. To mitigate this problem, the system applies a number of limitations on services.  
>
> The system distinguishes between foreground and background apps. (The definition of background for purposes of service limitations is distinct from the definition used by memory management; an app might be in the background as pertains to memory management, but in the foreground as pertains to its ability to launch services.) An app is considered to be in the foreground if any of the following is true:
>  - It has a visible activity, whether the activity is started or paused.
>  - It has a foreground service.
>  - Another foreground app is connected to the app, either by binding to one of its services or by making use of one of its content providers. For example, the app is in the foreground if another app binds to its:
>    - IME
>    - Wallpaper service
>    - Notification listener
>    - Voice or text service

And AhMyth probably can't pull it of, because it's a rat.
