### ISSUE TITLE
Lab doesn't display in win 10 64-bit (but opens)

### ISSUE THREAD

**Issue by krithick14** [AhMyth/AhMyth-Android-RAT#158]
lab opens but not visible in screen .I can drag the text in lab .but lab not displayed

**Comment by ErIMRANALAM** [comment]
11/11/2019, 1:23:47 PM Building Ahmyth.apk...
11/11/2019, 1:23:47 PM Building Failed

**Comment by defaultraw** [comment]
Exactly same problem. Open but not showing.

**Comment by krithick14** [comment]
> 11/11/2019, 1:23:47 PM Building Ahmyth.apk...
> 11/11/2019, 1:23:47 PM Building Failed

install java sdk
