### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by 01joker** [AhMyth/AhMyth-Android-RAT#16]
I am a Parrot Sec user and don't know how to start....
Help me for getting started

Thanks in advance.....

See the following error below

┌─[root@parrot]─[~]
└──╼ #npm -v
2.11.2

┌─[root@parrot]─[~/AhMyth-Android-RAT]
└──╼ #npm start

> @ start /root/AhMyth-Android-RAT
> electron ./app

sh: 1: electron: not found

npm ERR! Linux 4.11.0-parrot6-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ start: `electron ./app`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ start script 'electron ./app'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron ./app
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/AhMyth-Android-RAT/npm-debug.log

**Comment by ericklima88** [comment]
Did you try run npm install first?

**Comment by AhMyth** [comment]
It says "electron: not found"
install electron then try again
