### ISSUE TITLE
Adding source ip:port Failed

### ISSUE THREAD

**Issue by phspade** [AhMyth/AhMyth-Android-RAT#17]
How to fix this? Please improve this.. I like it's GUI.. <3
But it's to buggy for now but One day It'll be Perfect.. i suppose 💃

**Comment by jpacora** [comment]
Download from the repo and run npm start

**Comment by phspade** [comment]
I just fixed it by running it from root.. however, AhMyth should be prompt with Administrator in Linux when it's run by it's user :D

**Comment by phspade** [comment]
It should automatically check if AhMyth is run in Root or not.

**Comment by AhMyth** [comment]
@phspade Thanks for your feedback, I will improve it on next release.

**Comment by nehatkkhan786** [comment]
@phspade brother can you please tell how can i run Ahmyth as root in ubuntu 17.10! When i type sudo su ahmyth on my terminal it didnt work at all.  And when i run it without sudo command it works fine but can't build apk!  It say the same error the one you got at first.( Adding source ip: port failed)

**Comment by mirajhad** [comment]
Don't give any port number it will set to default port

**Comment by nehatkkhan786** [comment]
@mirajhad bro i did that but still its showing the same issue! i am on ubuntu 17.10. it was working fine but dont know whats wrong with that.

**Comment by charveey** [comment]
To solve this issue you just have to change the permissions of `/opt/AhMyth/resources/app.asar.unpacked/app/Factory/Ahmyth/smali/ahmyth/mine/king/ahmyth/IOSocket.smali `. Just make it writable by the user

**Comment by Hacker3541** [comment]
please open terminal as root and then type ahmyt
if it is not working then u will email me ur problem on kushagrasrivastav728@gmail.com

**Comment by JuniorClap** [comment]
----> Sudo apt install npm | it's Work
