### ISSUE TITLE
Client does not connect back

### ISSUE THREAD

**Issue by miaoski** [AhMyth/AhMyth-Android-RAT#18]
Hi.
I have `git clone` the repo, `npm i`, `npm start`, and everything worked really well.
I built several APKs with default setting, and it installed in Nexus image in Genymotion (tried Android 17, 19, 21).  However, the client does not connect back.

I am sure that there's no firewall issue.  I was able to download files from a `python -m SimpleHTTPServer` on the host to Genymotion VMs, and I tried `telnet 0 42474` the connection is accepted.

I have also tried the generated APKs on a real phone (4.2.2, Android 17).  It doesn't work, either.
Any clues for me?  Thank you!

**Comment by coptenekesi** [comment]
Did you get initial connection for every start? Then somehow clients lose connection and does not connect back?
