### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by krishnenduash** [AhMyth/AhMyth-Android-RAT#19]
how to install in kali linux  .. npn not war king....
.deb package install.. but building failt.. kali..32 bit

**Comment by AhMyth** [comment]
check [this](https://github.com/AhMyth/AhMyth-Android-RAT/issues/8)

**Comment by test32112** [comment]
Anyone with a good solution to the building failed error

**Comment by krishnenduash** [comment]
64 bit kali linux  work perfect
