### ISSUE TITLE
AhMyth-Android-RAT doesn't work on android 9 and 10 or original 2018-2019-2020 APK files 

### ISSUE THREAD

**Issue by Morsmalleo** [AhMyth/AhMyth-Android-RAT#193]
I am trying to establish a successful connection with AhMyth to my rooted Samsung Galaxy S7 running android 9 and LineageOS

I have successfully binded and built the AhMyth.s.apk file and have also successfully installed it on my Samsung phone 

but upon clicking "Listen" on AhMyth and opening the installed AhMyth app on my Samsung, nothing seems to happens on AhMyth's end!! 

it still just says "Listening on port 5555" and nothing else, i have used both methods of binding (On Boot & On Launcher Activity) and have even tried it without binding, and I still get the same results!!

Upon trying to use AhMyth against Android 9 and Android 10, I can see the results are the same.

unsure for android versions 6 & 8 

Please upgrade AhMyth to work on android 9 & 10 and hold support for 2018-2019-2020 apk files

**Comment by Morsmalleo** [comment]
If using a VirtualBox or VM make sure you have bridged adapter enabled or it wont work, and make sure you have port forward enabled for your router as well for AhMyth to work oitside of VM or Virtualbox

**Comment by constantinedev** [comment]
No not I have try to the say way going on Android 9 system with non rooted devices
it really not work for Android OS over 9....
