### ISSUE TITLE
.

### ISSUE THREAD

**Issue by vd062** [AhMyth/AhMyth-Android-RAT#196]

**Comment by Morsmalleo** [comment]
I am running android 9 with LineageOS on a Samsung Galaxy s7, now the issue
you have with the audio, is the same problem I am having with the Camera
when trying to snap photos using the front and back camera, it doesn't
work, it records audio but not at the greatest quality plus the amount of
seconds you input to be recorded, is a little buggy, for example, you type
in 10 seconds to be recorded, and it only records 8 or 9 seconds of it or
sometimes just a 1 second snippet, so yes @AhMyth you need to do some
updates to AhMyth

**Comment by Morsmalleo** [comment]
Very unstable with android versions after 6.0.1 as I've found out from the AhMyth owner on his twitter
