### ISSUE TITLE
APK Building failed in Windows x64 system  

### ISSUE THREAD

**Issue by sidjad** [AhMyth/AhMyth-Android-RAT#2]
steup was installed propely without any error . after trying to build apk without  bind apk option .
verbose window showing " Building failed " error 
![faild](https://user-images.githubusercontent.com/3491718/28241848-7b162bc2-69ba-11e7-9c72-87540cce83c0.PNG)

**Comment by knkrth** [comment]
Hi @sidjad, You need java in order to build the payload (.APK) You can download it from here http://www.oracle.com/technetwork/java/javase/downloads/index.html & let me know if it solved your problem.

**Comment by AhMyth** [comment]
as @knkrth said , you need to install java.

**Comment by sidjad** [comment]
it's working fine . Thanks

**Comment by piyush-basak17** [comment]
I have installed  Java SE Development Kit 9.0.1, still, it shows Building failed while generating the apk .
![image](https://user-images.githubusercontent.com/29175844/33119054-cafbe6a6-cf93-11e7-94f1-bf3a46798d9f.png)

**Comment by knkrth** [comment]
@piyush-basak17 Use  Java SE Development Kit 8

**Comment by piyush-basak17** [comment]
Still, It gets failed! Any fix?

**Comment by knkrth** [comment]
completely remove Java SE 9, env path And Install Java SE 8. For some reason Java SE 9 won't work.

**Comment by frizzyprogamer** [comment]
I reinstalled java 8 build 152 a lot of times and still not working for me.

**Comment by aadilnaina** [comment]
jdk-8u152-windows-x64.exe or jdk-8u151-windows-x64.exe  ??
Which need to Install by aadil

**Comment by Zerukhan123** [comment]
There should be something missing properly from our devices for this building failed error.  I do have java installed but still it doesn't work. A few people solved the problem but I am pretty sure it has something to do with Java version installed. Try all the settings and tell me what has worked for you and as for me I am still trying....

**Comment by BearBang7** [comment]
@sidjad  
What version exactly do you installed ?

**Comment by Javi-Schmidt** [comment]
I have installed jdk 8 and still the same error arises. What else can it be?

**Comment by Gameover333** [comment]
which java need to install
 please, friend, give total step
 --start from java install to binding apk built

**Comment by rhinfo1983** [comment]
easy my friends Building apk minor 2mb only

**Comment by rhinfo1983** [comment]
AhMyth only support android 6.0.1 and down

**Comment by rhinfo1983** [comment]
i tested 7.0 and 8.0 not working

**Comment by WheresLuo** [comment]
@rhinfo1983 what's platform you tested?

**Comment by rhinfo1983** [comment]
I tested 6.0.1 and 7.0 and 8.0, only work perfectly in 6.0.1 gps, récord
audio, sms, calle logs, snapshots :O

**Comment by rhinfo1983** [comment]
Oh plataform mmmm windows 7 64bits.

**Comment by bmwe46cl** [comment]
@rhinfo1983 
i need your help

**Comment by rajveerrv** [comment]
> steup was installed propely without any error . after trying to build apk without bind apk option .
> verbose window showing " Building failed " error
> ![faild](https://user-images.githubusercontent.com/3491718/28241848-7b162bc2-69ba-11e7-9c72-87540cce83c0.PNG)

do you find any solution?

**Comment by RoshanHacker** [comment]
Love U Bro this Is Working :D

**Comment by Raghuram0** [comment]
Hi guys I am getting build failed error 
I installed java jdk 8. 201 and I tried 202
Not working

**Comment by altamash1605** [comment]
how do we "fix building failed"?

**Comment by julio00004** [comment]
> 
> 
> AhMyth only support android 6.0.1 and down

hi, can't I just modify the manifest files and put the one of the latest version of android to work on android 8.0 and below?

**Comment by julio00004** [comment]
> 
> 
> That directory is inaccessible
> the error is because the cell phone has a pattern or pin ;(

but when is the cell phone  unlocked, Ahmyth function well?

**Comment by poojamaheria** [comment]
even i installed java 8 and tried to run AhMyth but same building failed error. can anyone please help?

**Comment by tasham1998** [comment]
i installed java 8 but even then i am getting the same building failed error. can anyone help?

**Comment by Arslan186** [comment]
> работает нормально Спасибо

What Java package did you install?

**Comment by venuharry** [comment]
jdk-8u152-windows-x64.exe

**Comment by Fisac** [comment]
i need help. i install jdk-13.0.1_window 64bit exe. am stilll getting error
![apkfail](https://user-images.githubusercontent.com/58230884/70386626-5b438b80-199b-11ea-9830-d1a20a007e4e.PNG)

**Comment by Irfanlesnar** [comment]
yes i too installed 13.0.1 still error tried all steps not working

**Comment by RezaEjtehadi** [comment]
install  **Java SE Runtime** not **kit**

**Comment by Mrblack007** [comment]
i install jdk 8 too...but still facing same error

**Comment by rockyhandsm2k** [comment]
See everyone ..NO ISSUE CAN BE SOLVED IF WE JUST TALKED ABOUT TYE THIBGS THAT DIDNT WORKED....IF ANYONE HAVE A CLUE OF ANY SUGGESTION WORKED FOR HIM/HER...PLEASE REPLY

**Comment by rockyhandsm2k** [comment]
> install **Java SE Runtime** not **kit**

Does that worked for you?

**Comment by Mrblack007** [comment]
Firstly uninstall every thing... After that instal jdk 8 only the install AhMyth setup for windows... It will work

**Comment by Mrblack007** [comment]
> > install **Java SE Runtime** not **kit**
> 
> Does that worked for you?

Install jdk 8 then install AhMyth (not with binary) I'll work InshaAllah

**Comment by rockyhandsm2k** [comment]
THIS IS A MESSAGE TO ALL COMMUNITY......I HAVE FOUND THE REASON BEHIND IT..... INSTALL JAVA SE RUNTIME AND AHMYTH AND NOT JUST RUN JAVA BEFORE BULDING APK ..FOR THIS GO TO CMD AND TYPE java AND HIT ENTER , NOW TRY BUILDING APK IT WILL VULD SUCCESSFULLY.....as the problem was that it was not able to run automatically so we need to run it manually......like is u solved..cheers for victory

**Comment by Gokulkannan007** [comment]
Hello friends I am facing trouble with the ahmyth.It states that the" building Failed".what can I do now.

**Comment by Gokulkannan007** [comment]
I have also installed Java SE RUNTIME and I had also rubbed it at terminal.

**Comment by Gokulkannan007** [comment]
Yeah you are right rocky it did work for me.Thank you

**Comment by Llensom525** [comment]
I have the same problem, but I try to build it with another apk.
Building it without any apk if it is built

**Comment by Llensom525** [comment]
![ahmyth](https://user-images.githubusercontent.com/60831667/80042336-56075900-84c4-11ea-91d2-0ddd55850c33.png)

**Comment by Llensom525** [comment]
![ahmyth3-2](https://user-images.githubusercontent.com/60831667/80042357-63bcde80-84c4-11ea-9ae2-d50e48f790c8.png)

**Comment by davenisc** [comment]
esto no sirve!

**Comment by salmanfairoze** [comment]
Atleast where do we find Logs so that we can debug on our own?

**Comment by Gokulkannan007** [comment]
Just install the python and run it in the CMD and open the ahmyth it worked
for me.I hope that this could help you.

On 9 May 2020 12:15 am, "salmanfairoze" <notifications@github.com> wrote:

Atleast where do we find Logs so that we can debug on our own?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/AhMyth/AhMyth-Android-RAT/issues/2#issuecomment-625960652>,
or unsubscribe

**Comment by natiethiopia** [comment]
Trying to bind with the original apk, some times it works and some times I get "Building Failed".
Java is already installed.
Please help

**Comment by salmanfairoze** [comment]
Ensure if you have JAVA Runtime (JRE) in particular. Having that solved
everyone's issue, even mine.

**Comment by P1n3pple** [comment]
> Hi @sidjad, You need java in order to build the payload (.APK) You can download it from here http://www.oracle.com/technetwork/java/javase/downloads/index.html & let me know if it solved your problem.

i did that, still not working

**Comment by Maheshbhoopati** [comment]
Yes it is working Thanks bro .

**Comment by Maheshbhoopati** [comment]
But build over another apk failed .
![Annotation 2020-07-08 133914](https://user-images.githubusercontent.com/66664139/86894444-b2236600-c120-11ea-9b35-73d47fa58952.png)

**Comment by moTorky** [comment]
i have same problem ,
and i also have java in my pc 

"C:\Users\power>java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)"
help my ...

**Comment by moTorky** [comment]
when i install apk file on my mobile, its crash ,
and i can't debug the apk file in android studio 
  any one have a solution of this problem...

**Comment by Nodir3df** [comment]
Почти все java установил не один сработал, а потом оказался что блокировал мой антивирус, сначала отключите антивирус для этой программы а потом все будет на отлично

**Comment by adityapriyadarshi669** [comment]
Download JAVA SE RUNTIME https://www.oracle.com/java/technologies/javase-jre8-downloads.html
It Worked for me. :)

**Comment by DivyT-03** [comment]
Nothing Worked
Turned off Defender and Everything worked

**Comment by ZBashev** [comment]
Nothing Worked

**Comment by MrOdball** [comment]
Actually, nothing works may be ahmyth can't detect java can anyone tell how to add java path manually in ahmyth
I think ahmyth uses default file path of java but now oracle java path has been changed 
I don't know whatever the reason is but i think it's likely to be 

btwn , Please anyone guide me to add java file path manually . . .

**Comment by BOW789** [comment]
can you all give a tutorial on how to run ahmyth

**Comment by xXZ3HERXx** [comment]
I Tried All java versions I Couldnt Run

**Comment by slavaloki** [comment]
Отключите антивирус и в стандартном защитнике разрешите проге работать!

**Comment by AbdouBhn** [comment]
for whoever still have this problem ,i had the same error in Droidjack too ,they were not able to create APK file
- Just disable windows defender real time protection and Go disable it from Registry too (if you don't know how search on youtube how to disable windows defender permanently) 
apparently windows defender keep cutting off the process while they create apk files
