### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by olafdedj** [AhMyth/AhMyth-Android-RAT#25]
No matter what i try it always says that the build has failed...

it says : building failed

**Comment by AhMyth** [comment]
Which OS are you using ?
Did you try it on another OS ?

**Comment by sanket7941** [comment]
i have the same problem I'm using windows 10 home x64bit
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
