### ISSUE TITLE
Error while starting [ npm start ] 

### ISSUE THREAD

**Issue by IM-TECHNO** [AhMyth/AhMyth-Android-RAT#251]
When i try to start, i get the following output : 

> start
> npx electron ./app

glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
[5581:1125/110343.372927:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/techno/pentest/AhMyth-Android-RAT/AhMyth-Server/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.

**Comment by MichaelTheBui** [comment]
Are you the admin on your computer?

**Comment by IM-TECHNO** [comment]
Yes

**Comment by Morsmalleo** [comment]
You need to open terminal and CD into the following repositories, for yourself it would be the following below;

Kali@Kali~: cd /home/techno/pentest/AhMyth-Android-RAT/AhMyth-Server/node_modules/electron/dist/

Find the Chrone-sandbox file, and type the following syntax commands 

Kali@kali~: sudo chown root chrome-sandbox
Kali@kali~: sudo chmod 4755 chrome-sandbox 

After this "chrome-sandbox should be highlighted in red, if its highlighted in ref you are good to go, 

NOTE: ALWAYS do the  "chown root chrome-sandbox" first
And always do the "chmod 4755 chrome-sandbox" second

**Comment by Morsmalleo** [comment]
You may have trouble using AhMyth altogether since it needs openjdk-8-jdk to run properly, since openjdk-8-jdk is no longer supported for Debian 10 its will prove difficult

**Comment by IM-TECHNO** [comment]
Thanks ! **Everything works fine** now
