### ISSUE TITLE
Signing Failed

### ISSUE THREAD

**Issue by vladislav2402** [AhMyth/AhMyth-Android-RAT#256]
![image](https://user-images.githubusercontent.com/72248804/102255843-4e913600-3f13-11eb-8367-02e3aff85f4b.png)
How to fix it..?

**Comment by runetech0** [comment]
Having the same issue. Did anyone find a solution to the problem?

**Comment by Oftroll** [comment]
me too

**Comment by ZeroCoolHacker** [comment]
bump

**Comment by Morsmalleo** [comment]
Use openjdk-8-jdk from Debian Stretch to fix this problem
