### ISSUE TITLE
Interface doesn't work after installing electron-nightly

### ISSUE THREAD

**Issue by Morsmalleo** [AhMyth/AhMyth-Android-RAT#260]
I have installed everything correctly, i have even installed openjdk-8-jdk update 181 (Java 1.8.0_181)m but the interface refuses to work at all, never had a problem up until now, without electron-nightly I can build standalone payload apk files, but I cannot bind with any apk file, the window to browse the apk file opens, but upon selecting the apk, the window closes and nothing happens, but upon installing electron-nightly which used to be what fixed that problem, the damned interface doesn't work at all, i can't exit, i cant minimize, I can't select the apk builder, I can't do a thing 

this is the installation process

git clone https://github.com/AhMyth/AhMyth-Android-RAT.git
cd AhMyth-Android-RAT
cd AhMyth-Server
npm install 

it says there is one package that needs to be audit fixed, so i did, also i have even tried it without fixing it, the same problem arises after installing electron-nightly, anyway the rest of the installation process below,

npm audit fix 
npm start 

so from here everything works, i can build standalone apks, but I cannot choose an Original apk to bind with, nothing happens upon selecting the original APK file i want to bind with, that's where I used to use electron-nightly to fix the problem, only back then it was called electron@nightly, probably an older version of what gets installed now

npm install electron-nightly 
npm start

now the damn interface doesn't work at all, I try installing electron 9.0.0

npm install electron@9.0.0

the interface still does not work, i have even tried switching java versions via update-alternatives but nothing wants to make it work, something has gone wrong somewhere with electron-nightly either that or the current version of electron-nightly doesn't support AhMyth, and it needs to be fixed otherwise this project may as well be labelled as DEAD

**Comment by asd339** [comment]
не работает интерфейс!

**Comment by Morsmalleo** [comment]
Issue fixed just run 
`npm uninstall electron-nightly && npm uninstall electron-rebuild` 

Then by removing the `chmod 4755` permissions from `chrome-sandbox` as well as removing the owner permissions that were set by running `chown root chrome-sandbox`

Then start AhMyth
`npx electron ./app --no-sandbox start` 
Or just run
`npm start`
