### ISSUE TITLE
Compiled the latest version? 

### ISSUE THREAD

**Issue by Dazmed707** [AhMyth/AhMyth-Android-RAT#265]
How to download the latest versión in .exe ?

**Comment by BadMaliciousPyScripts** [comment]
Well just download electron and follow the description. Its really easy even someone who has never worked with electron before is able to do this.

**Comment by BadMaliciousPyScripts** [comment]
And also have a look at following: [AhMyth-Modified-Version](https://github.com/HiddenPirates/AhMyth-Modified-Version)
They should have made what you're looking for.

**Comment by Dazmed707** [comment]
Ok, thanks :)
