### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by sabrex123** [AhMyth/AhMyth-Android-RAT#3]
$ cd /root/Desktop/AhMyth-Android-RAT
$ npm start 

Result
> @ start /root/Desktop/AhMyth-Android-RAT
> electron ./app

sh: 1: electron: not found

npm ERR! @ start: `electron ./app`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron ./app
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.0-kali4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /root/Desktop/AhMyth-Android-RAT
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/Desktop/AhMyth-Android-RAT/npm-debug.log
npm ERR! not ok code 0

i need help here. Thanks

**Comment by samdenty99** [comment]
You need to download & install the [Electron framework](https://electron.atom.io/releases/)

**Comment by sabrex123** [comment]
thankss
