### ISSUE TITLE
Compiling in windows?

### ISSUE THREAD

**Issue by narcomerk19** [AhMyth/AhMyth-Android-RAT#30]
Is there any tool to compile it on windows, specifically in win10 64bit? Should I need some linux stuff ?

**Comment by AhMyth** [comment]
Donwload the "ready to install" binary from [here](https://github.com/AhMyth/AhMyth-Android-RAT/releases/download/v1.0-beta.1/AhMyth_Win64.exe).
and Download JDK from [here](http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-windows-x64.exe).

and that is it.

**Comment by narcomerk19** [comment]
@AhMyth

thanks man for your helpful links..

**Comment by mario6714** [comment]
i have a problem, already installed java and jdk and still dont work

build 64 Bits and Windows 10 64 Bits

**Comment by maxrep66** [comment]
i have a problem i wanna solve i use kali linux 2018.1 after i build the apk now say build failed 
i have all as i did before 
i have node i have npm but i have problem not build help pls
