### ISSUE TITLE
NPM error while running npm start

### ISSUE THREAD

**Issue by pariyopatel90** [AhMyth/AhMyth-Android-RAT#31]
hi 
i am using Kali. when i give command npm start it gives me this error

npm ERR! path /root/AhMyth-Android-RAT/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/root/AhMyth-Android-RAT/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-20T13_42_10_083Z-debug.log

**Comment by AhMyth** [comment]
```
cd AhMyth-Android-RAT/AhMyth-Server
npm start
```

**Comment by pariyopatel90** [comment]
i did the same when i give command npm start it gave me above mentioned error.

**Comment by coptenekesi** [comment]
if you do not have the required node modules, you should "npm install" first. And then try to start app.

**Comment by alxizr** [comment]
navigate to (in my test case i put the folder on the desktop)
C:\Users\__yourusername__\Desktop\AhMyth-Android-RAT\AhMyth-Server 

run install packages command
npm install electron electron-builder electron-packager --save-dev

run launch command
npm start --unsafe-perm
