### ISSUE TITLE
Does Ahmyth Really work with a public IP address?

### ISSUE THREAD

**Issue by hiitsmemee6** [AhMyth/AhMyth-Android-RAT#35]
I tried building an apk with my public IP address but victims wont show up in the list.But in local IP address victims are there.Please help

**Comment by AhMyth** [comment]
If it is work on private network then it should also work on public network unless you have network misconfiguration.

**Comment by hiitsmemee6** [comment]
We are talking about Private=Devices on the same network and Public=Devices on different networks right?

If so Ahmyth works on my private network, but not on public networks.What do i fill in the IP address box if i want it to be working on public networks.I am willing to donate to this app because personally i think its great and will be greater if you fix my problen

**Comment by peonot** [comment]
@hiitsmemee6 

1. Port forward 42474.
2. When building the apk you should use your **public IP** and the default port (42474)
3. Listen to 42474 in the Victims tab.

(P.s. You can get into big trouble for doing this, I will not be responsible for whatever you do with this information.)

**Comment by hiitsmemee6** [comment]
@peonot It is legal in my country,also i tried that before with my IP 175.XXX.XXX.X it didnt work :( how did you get yours working?
good i catched you online

**Comment by hiitsmemee6** [comment]
I did not test it using different networks, But when i built the ahmyth.s.apk i used my public IP but my android device was connected to the same network.

**Comment by peonot** [comment]
@hiitsmemee6 
If you used your **public IP** and it worked, it should work as long as the **victim** is connected to the internet. 
Also make sure that **you** are connected to your home wifi (the one that you port forwarded).

**Comment by peonot** [comment]
Just curious... how are you even going to install the apk on the victims phone?

**Comment by hiitsmemee6** [comment]
@peonot social engineering my friend

**Comment by hiitsmemee6** [comment]
ill try this tommorow

**Comment by hiitsmemee6** [comment]
Quick question, Will any random port work(including deafult one) as long as i made the apk in the same network?

**Comment by peonot** [comment]
@hiitsmemee6 
It will but it's not recommended because you might use a port that is already used by other apps/programs.

**Comment by hiitsmemee6** [comment]
Well that was a waste of time.... It doesnt work

**Comment by hiitsmemee6** [comment]
Time to look for a new RAT

**Comment by astrayal** [comment]
I dont know why, This one is working great for managing my devices bot on lan and over the internet all over town.

**Comment by astrayal** [comment]
NOTE I'M RUNNING LATEST UBUNTU 17
AND TO PROPERLY BUILD THE APKS I MUST RUN IT UNDER SUDO
IE
[CODE]sudo ahmyth[/CODE]

**Comment by abhilash62** [comment]
same issue to me. public ip address does not work

**Comment by astrayal** [comment]
Listen Guys, 
it works for me on every network and even over 4g lte data on the devices.
You HAVE to FOrward your Ports on both your routers and your gateway , then you have to also open the ports on your pc in your firewall.
that did it for me.
the option to modify an existing apk doesnt work , thinking jarsign is signing it and then with conflicting package sig.s it don't install.
BUT the option to just create Ahmyth.apk
Does work.
I'm commenting here today because i'm tired of all the whining in my email box.
So like if your going to use software like this... but you dont know to open your router and firewalls, you should probably try a different software.
THIS IS NOT A TOY.
as an easier alternative, maby try
https://play.google.com/store/apps/details?id=com.webkey&hl=en

it also works, and is easier to set up.
NOW GO READ YOUR DOCUMENTATION AND THE FAQ and quite filling my mailbox up with
"waaah it dont work."

**Comment by abhilash62** [comment]
its correct but I am accessing internet through usb tethering via my mobile
phone. so no port forwarding wizard available. any solution for that?

**Comment by astrayal** [comment]
<its correct but I am accessing internet through usb tethering via my mobile
phone. so no port forwarding wizard available. any solution for that? >

openvpn server at amazon ec2 aws free tier. and a reverse ssh tunnel either one of those along with a bit of iptables will get you there.

google it

…

**Comment by seanho12345** [comment]
@astrayal What protocol should I use for forwarding that port?
And Should I just set the public and private port to 42747?

**Comment by ujjawalhub** [comment]
> open the ports on your pc in your firewall

Bro, tell me the config for SSH -R and the port forwarding as per the AhMyth input IP and port.
it will be very helpful for me....!

**Comment by rubelahm** [comment]
please help me if anyone see this comments plese reply me

**Comment by rubelahm** [comment]
really it work when victims connected other network?  please tell me anyone 😟😟

**Comment by radioactive-banana** [comment]
**connect to victim over WAN**

1. Download [ngrok] https://ngrok.com/
2.follow the procedure to save authtoken to configuration file
![image](https://user-images.githubusercontent.com/69292586/92303443-7ecf4d00-ef92-11ea-9669-56741d29204b.png)

**Comment by eshX404** [comment]
How can i set up the port forwarding part in RDP?
