### ISSUE TITLE
Won't run on bounded apk

### ISSUE THREAD

**Issue by p1vynodejs** [AhMyth/AhMyth-Android-RAT#4]
I have created a custom apk, turn a website to android app using webview.

I bound it to my apk. after installing it on my phone, happens. It wont show on the victim list

**Comment by p1vynodejs** [comment]
i've managed to get the .java files of the rat apk and combine it with my app manually. 

the only problem now is the service closes when the app is forced closed.

**Comment by AhMyth** [comment]
"It wont show on the victim list" --> do you try it on same network ?

**Comment by p1vynodejs** [comment]
no, the host is on my vps, and victim is my phone. when i used the raw apk (without apk bounded), it runs smoothly. but when i bound it to my apk, no victim shows...

anyway, i managed to get the java codes and insert my code on it manually. it's working now. i will soon explore the nodejs files to add more function. atm, I added "inbox" and "sent" items via client source.
