### ISSUE TITLE
the backdoor dont work on my android device and nothing shown on victims list 

### ISSUE THREAD

**Issue by Hassan-Abd-Elaziz** [AhMyth/AhMyth-Android-RAT#6]

**Comment by AhMyth** [comment]
did you try it on same network ?

**Comment by Hassan-Abd-Elaziz** [comment]
yes but nothing happen

**Comment by AhMyth** [comment]
check your firewall config

which OS are you using and which android device ?

**Comment by usama7628674** [comment]
It's working fine for me on Windows 10 pro 64 bit.

**Comment by Hassan-Abd-Elaziz** [comment]
AhMyth My phone running on android 6.0

**Comment by usama7628674** [comment]
My android is also 6.0,working fine though.
