### ISSUE TITLE
Building failed

### ISSUE THREAD

**Issue by Qurexhi** [AhMyth/AhMyth-Android-RAT#7]
jave install but still building failed

![28241848-7b162bc2-69ba-11e7-9c72-87540cce83c0](https://user-images.githubusercontent.com/17900900/28498315-dcf659f8-6fb3-11e7-85a4-3a174826e63c.PNG)

**Comment by AhMyth** [comment]
try to run java on CMD like "java -version" , it should print the java version , if not then add java to environment variables.

**Comment by Qurexhi** [comment]
problem still not solve..

![2017-07-25_023954](https://user-images.githubusercontent.com/17900900/28546071-d202bade-70e2-11e7-9181-168ebd4506be.jpg)

**Comment by doctordeep** [comment]
Maybe you're running a 32bit distro. Was have same problem on kali 32b after install kali 64bit (used npm to install electron-builder and not yarn) the software started build and work with my phone in a local area network

**Comment by mario6714** [comment]
same problem and i have java installed

**Comment by test32112** [comment]
Anyone with a good solution to the building failed error

**Comment by BearBang7** [comment]
Same HERE : Java -Version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**Comment by tofa7** [comment]
same here 

#java -version
openjdk version "11.0.5-ea" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5-ea+6-post-Debian-2)
OpenJDK 64-Bit Server VM (build 11.0.5-ea+6-post-Debian-2, mixed mode)
