### ISSUE TITLE
building failed

### ISSUE THREAD

**Issue by amainyebriggs** [AhMyth/AhMyth-Android-RAT#8]

**Comment by p1vynodejs** [comment]
install java

**Comment by Jarthromann** [comment]
Make sure you don't have listen enabled before building the apk. I know this is a old post but people might need to know this.

**Comment by amainyebriggs** [comment]
listen is also disabled

**Comment by alphaaurigae** [comment]
hi similar problems here
, writing install and run scripts but point 2 failed - python2 & 3 .See latest issue reports

**Comment by doctordeep** [comment]
Maybe you're running a 32bit distro. Was have same problem on kali 32b after install kali 64bit (used npm to install electron-builder and not yarn) the software started build and work with my phone in a local area network

**Comment by test32112** [comment]
Anyone with a good solution to the building failed error

**Comment by thupsy** [comment]
also have the same problem . kali linux 64bit java installed . but still apk building failed .

**Comment by djroyald** [comment]
i too have this same problem

**Comment by djroyald** [comment]
or how many have used this before?

**Comment by aresthunder1** [comment]
Not all apps will work
