### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by Verruckterman** [AhMyth/AhMyth-Android-RAT#87]
please help me i can't understand this error how to fix it
![capture du 2018-04-26 23-48-20](https://user-images.githubusercontent.com/8110285/39333866-c7a7f416-49ac-11e8-8d77-c35d24abbf8e.png)

**Comment by djmeero** [comment]
Do you have electron installed? If not try "npm install electron --save-dev"

**Comment by emptix0** [comment]
Im getting the same error, and yes I have electron installed.

**Comment by Verruckterman** [comment]
i have the same Problem

![capture du 2018-04-28 21-52-55](https://user-images.githubusercontent.com/8110285/39400331-bd8ee718-4b2e-11e8-9de1-85399d0fa6dd.png)

**Comment by TRKBKR** [comment]
sudo apt-get install nodejs-legacy
